### PR TITLE
Query all jobs

### PR DESCRIPTION
**Pull request by webmaster128**

### CODE REVIEW

**Review by kaisbaccour — APPROVED** [review]
Very nice, looks like it was a lot of work.
So I guess when we query the unprocessed jobs we always need to set a reasonable round decimal range otherwise the request would kill the rpc node with the long loop oris my understanding not correct?

**Comment by webmaster128** [comment]
> looks like it was a lot of work.

Was okay, not crazy. Most of the diff is the separation of the stare.rs file into a state folder to get more clarity what's going on. Only the `all_unprocessed_drand_jobs` implementation is new.

>  So I guess when we query the unprocessed jobs we always need to set a reasonable round decimal range otherwise the request would kill the rpc node with the long loop oris my understanding not correct?

The jobs are removed when processed. So the number of DB entries should be small. However, over time we have a lot of `Deque`s that has a head/tail meta entry in the storage that we loop through even if the Deque has no jobs anymore. This makes it inefficient in the long run.

RPC nodes have per-node gas limit. I think you will hit this at some point but not hurt the node. Then you can increase it in your node when you need costy queries.

In the long run, we need to organize jobs differently. But this should allow us to make some progress client side.

**Comment by kaisbaccour** [comment]
What do you think is the best way to query the rounds with unprocessed (and processed) jobs on drand-contract? I attempted something on the other PR but not sure if that's the nicest way to do things.

**Comment by webmaster128** [comment]
> What do you think is the best way to query the rounds with unprocessed (and processed) jobs on drand-contract?

The current storage layout makes this very hard as it was never designed for this. With this PR a client can use the Jobs queries and then look at the `source` fields of the jobs to find the round.

**Comment by kaisbaccour** [comment]
Sorry I gave too little context over what I want to achieve. On the drand-contract I have a specific round that I want to query on. All I want to know is if there are any unprocessed or processed jobs for a specific round to be able to incentivise bots for that round. Now I am using the old gateway query msg to check on jobs corresponding to a specific round. The only thing is I cannot use the crate of gateway because then we get some duplicate resources. So I just tried to externalise a couple structs from gateway  to package and then use that for both gateway and drand. 
Do you think there's a better way to achieve this?

**Pull request merged**
